import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import analyzer
import os
import datetime

# Setup
intel = analyzer.MarketIntelligence()
df = intel.df

# --- HTML TEMPLATE ---
html_template = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Job Market Snapshot 2026</title>
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&display=swap');
        
        body {{ font-family: 'Inter', sans-serif; background: #f8f9fa; margin: 0; padding: 40px 20px; color: #111; }}
        .container {{ max-width: 1200px; margin: 0 auto; background: #fff; padding: 60px; box-shadow: 0 10px 40px rgba(0,0,0,0.03); border-radius: 12px; }}
        
        h1 {{ font-size: 3.5rem; font-weight: 800; letter-spacing: -2px; margin-bottom: 0.1em; color: #111; }}
        h1 span {{ color: #0055FF; }}
        
        .subtitle {{ color: #666; font-size: 1.2rem; margin-bottom: 60px; border-bottom: 3px solid #111; padding-bottom: 20px; display: flex; justify-content: space-between; }}
        
        .kpi-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 30px; margin-bottom: 60px; }}
        .kpi-card {{ background: #fff; padding: 25px; border-radius: 8px; border: 1px solid #eee; border-left: 4px solid #0055FF; transition: transform 0.2s; }}
        .kpi-card:hover {{ transform: translateY(-5px); box-shadow: 0 5px 15px rgba(0,0,0,0.05); }}
        
        .kpi-val {{ font-size: 2.8rem; font-weight: 700; line-height: 1; color: #111; }}
        .kpi-label {{ font-size: 0.85rem; text-transform: uppercase; color: #666; letter-spacing: 1px; margin-top: 10px; font-weight: 600; }}
        
        .chart-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 50px; margin-bottom: 60px; }}
        .section-title {{ font-size: 1.4rem; font-weight: 700; margin-bottom: 25px; border-left: 4px solid #111; padding-left: 15px; display: flex; align-items: center; }}
        .section-title span {{ color: #0055FF; margin-right: 10px; }}
        
        .footer {{ margin-top: 80px; font-size: 0.9rem; color: #888; text-align: center; border-top: 1px solid #eee; padding-top: 30px; }}
        
        @media(max-width: 768px) {{ .kpi-grid, .chart-grid {{ grid-template-columns: 1fr; }} .container {{ padding: 20px; }} }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Jobs.cz <span>Insight</span></h1>
        <div class="subtitle">
            <span>Weekly Market Intelligence Report</span>
            <span>{date}</span>
        </div>

        <div class="kpi-grid">
            <div class="kpi-card">
                <div class="kpi-val">{total_jobs}</div>
                <div class="kpi-label">Active Signals</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-val">{med_salary}k</div>
                <div class="kpi-label">Median Wage (CZK)</div>
            </div>
             <div class="kpi-card">
                <div class="kpi-val">{remote_share}%</div>
                <div class="kpi-label">True Remote</div>
            </div>
             <div class="kpi-card">
                <div class="kpi-val">{en_share}%</div>
                <div class="kpi-label">English Friendly</div>
            </div>
        </div>

        <div class="chart-grid">
            <div>
                <div class="section-title"><span>01</span> Source Distribution</div>
                <div id="chart_source"></div>
            </div>
            <div>
                <div class="section-title"><span>02</span> Contract Types</div>
                <div id="chart_contract"></div>
            </div>
        </div>

        <div class="chart-grid">
            <div>
                <div class="section-title"><span>03</span> Tech Stack Gap</div>
                <div id="chart_tech"></div>
            </div>
            <div>
                <div class="section-title"><span>04</span> Salary by Platform</div>
                <div id="chart_salary"></div>
            </div>
        </div>

        <div class="footer">
            Generated by <a href="https://github.com/hiddenmany/jobinsight_czechia" style="color:#0055FF; font-weight:bold; text-decoration:none;">JobsCzInsight</a> Cloud Scraper.
        </div>
    </div>
    
    <script>
        var source_data = {json_source};
        Plotly.newPlot('chart_source', source_data.data, source_data.layout);

        var contract_data = {json_contract};
        Plotly.newPlot('chart_contract', contract_data.data, contract_data.layout);

        var tech_data = {json_tech};
        Plotly.newPlot('chart_tech', tech_data.data, tech_data.layout);

        var salary_data = {json_salary};
        Plotly.newPlot('chart_salary', salary_data.data, salary_data.layout);
    </script>
</body>
</html>
"""

# --- KPI CALCULATION ---
med_sal = df[df['avg_salary']>0]['avg_salary'].median()
med_sal_fmt = int(med_sal/1000) if pd.notna(med_sal) else "N/A"

# Robust KPI extraction
remote_truth = intel.get_remote_truth()
remote_share = int(remote_truth.get('True Remote', 0) / len(df) * 100) if len(df) > 0 else 0

lang_barrier = intel.get_language_barrier()
en_friendly = lang_barrier.get('English Friendly', 0)
en_share = int(en_friendly / len(df) * 100) if len(df) > 0 else 0

# --- CHART GENERATION (JSON) ---
# Common layout settings
layout_defaults = dict(
    margin=dict(l=0,r=0,t=0,b=0),
    height=300,
    paper_bgcolor='rgba(0,0,0,0)',
    plot_bgcolor='rgba(0,0,0,0)',
    font=dict(family='Inter, sans-serif', color='#111')
)

# 1. Source Distribution
vol_stats = df['source'].value_counts()
fig_vol = px.bar(vol_stats, orientation='h', color_discrete_sequence=['#111'])
fig_vol.update_layout(**layout_defaults)
fig_vol.update_traces(marker_color='#0055FF') # Blue bars

# 2. Contract Types
contracts = intel.get_contract_split()
# Palette: Blue (Main), Dark Gray, Light Gray
fig_cont = px.pie(
    values=list(contracts.values()), 
    names=list(contracts.keys()), 
    hole=0.6, 
    color_discrete_sequence=['#0055FF', '#333333', '#CCCCCC'] 
)
fig_cont.update_layout(**layout_defaults)

# 3. Tech Stack
stack = intel.get_tech_stack_lag()
df_stack = pd.DataFrame([
    {"Type": "Modern", "Count": stack.get('Modern', 0)}, 
    {"Type": "Legacy", "Count": stack.get('Dinosaur', 0)}
])
fig_tech = px.bar(df_stack, x="Count", y="Type", color="Type", color_discrete_map={"Modern": "#0055FF", "Legacy": "#333333"})
fig_tech.update_layout(**layout_defaults)

# 4. Salary by Platform
plat_stats = df[df['avg_salary'] > 0].groupby('source')['avg_salary'].median().sort_values(ascending=True)
fig_sal = px.bar(plat_stats, orientation='h', color_discrete_sequence=['#333'])
fig_sal.update_layout(**layout_defaults)
fig_sal.update_traces(marker_color='#111')

# --- RENDER ---
output_html = html_template.format(
    date=datetime.date.today().strftime("%d. %B %Y"),
    total_jobs=len(df),
    med_salary=med_sal_fmt,
    remote_share=remote_share,
    en_share=en_share,
    json_source=fig_vol.to_json(),
    json_contract=fig_cont.to_json(),
    json_tech=fig_tech.to_json(),
    json_salary=fig_sal.to_json()
)

# Ensure 'public' dir exists
os.makedirs("public", exist_ok=True)
with open("public/index.html", "w", encoding="utf-8") as f:
    f.write(output_html)

print("Static report generated: public/index.html")
