import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import analyzer
import os
import datetime

# Setup
intel = analyzer.MarketIntelligence()
df = intel.df

# --- HTML TEMPLATE ---
html_template = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Job Market Snapshot 2026</title>
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
    <style>
        body {{ font-family: 'Inter', sans-serif; background: #f4f4f4; margin: 0; padding: 20px; color: #111; }}
        .container {{ max-width: 1200px; margin: 0 auto; background: #fff; padding: 40px; box-shadow: 0 4px 20px rgba(0,0,0,0.05); border-radius: 8px; }}
        h1 {{ font-size: 3rem; font-weight: 800; letter-spacing: -1px; margin-bottom: 0.2em; }}
        .subtitle {{ color: #666; font-size: 1.1rem; margin-bottom: 40px; border-bottom: 2px solid #000; padding-bottom: 20px; }}
        .kpi-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin-bottom: 40px; }}
        .kpi-card {{ background: #fafafa; padding: 20px; border-radius: 4px; border-left: 4px solid #000; }}
        .kpi-val {{ font-size: 2.5rem; font-weight: 700; line-height: 1; }}
        .kpi-label {{ font-size: 0.8rem; text-transform: uppercase; color: #666; letter-spacing: 1px; margin-top: 5px; }}
        .chart-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 40px; margin-bottom: 40px; }}
        .section-title {{ font-size: 1.5rem; font-weight: 700; margin-bottom: 20px; border-left: 4px solid #333; padding-left: 10px; }}
        .footer {{ margin-top: 60px; font-size: 0.8rem; color: #888; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }}
        .badge {{ background: #000; color: #fff; padding: 4px 8px; border-radius: 4px; font-size: 0.8rem; }}
        @media(max-width: 768px) {{ .kpi-grid, .chart-grid {{ grid-template-columns: 1fr; }} }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Jobs.cz Insight</h1>
        <div class="subtitle">Weekly Market Intelligence Report // Generated: {date}</div>

        <div class="kpi-grid">
            <div class="kpi-card">
                <div class="kpi-val">{total_jobs}</div>
                <div class="kpi-label">Active Signals</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-val">{med_salary}k</div>
                <div class="kpi-label">Median Wage (CZK)</div>
            </div>
             <div class="kpi-card">
                <div class="kpi-val">{remote_share}%</div>
                <div class="kpi-label">True Remote</div>
            </div>
             <div class="kpi-card">
                <div class="kpi-val">{en_share}%</div>
                <div class="kpi-label">English Friendly</div>
            </div>
        </div>

        <div class="chart-grid">
            <div>
                <div class="section-title">01 // Source Distribution</div>
                <div id="chart_source"></div>
            </div>
            <div>
                <div class="section-title">02 // Contract Types</div>
                <div id="chart_contract"></div>
            </div>
        </div>

        <div class="chart-grid">
            <div>
                <div class="section-title">03 // Tech Stack Gap</div>
                <div id="chart_tech"></div>
            </div>
            <div>
                <div class="section-title">04 // Salary by Platform</div>
                <div id="chart_salary"></div>
            </div>
        </div>

        <div class="footer">
            Generated by <a href="https://github.com/hiddenmany/jobinsight_czechia" style="color:#000; font-weight:bold;">JobsCzInsight</a> Cloud Scraper.
        </div>
    </div>
    
    <script>
        var source_data = {json_source};
        Plotly.newPlot('chart_source', source_data.data, source_data.layout);

        var contract_data = {json_contract};
        Plotly.newPlot('chart_contract', contract_data.data, contract_data.layout);

        var tech_data = {json_tech};
        Plotly.newPlot('chart_tech', tech_data.data, tech_data.layout);

        var salary_data = {json_salary};
        Plotly.newPlot('chart_salary', salary_data.data, salary_data.layout);
    </script>
</body>
</html>
"""

# --- KPI CALCULATION ---
med_sal = df[df['avg_salary']>0]['avg_salary'].median()
med_sal_fmt = int(med_sal/1000) if pd.notna(med_sal) else "N/A"
remote_share = int(intel.get_remote_truth()['True Remote'] / len(df) * 100)
en_share = int(intel.get_language_barrier()['English Friendly (Ocean)'] / len(df) * 100)

# --- CHART GENERATION (JSON) ---
# 1. Source Distribution
vol_stats = df['source'].value_counts()
fig_vol = px.bar(vol_stats, orientation='h', color_discrete_sequence=['#111'])
fig_vol.update_layout(margin=dict(l=0,r=0,t=0,b=0), height=300, paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')

# 2. Contract Types
contracts = intel.get_contract_split()
fig_cont = px.pie(values=list(contracts.values()), names=list(contracts.keys()), hole=0.5, color_discrete_sequence=px.colors.sequential.Gray)
fig_cont.update_layout(margin=dict(l=0,r=0,t=0,b=0), height=300)

# 3. Tech Stack
stack = intel.get_tech_stack_lag()
df_stack = pd.DataFrame([{"Type": "Modern", "Count": sum(stack['Modern'].values())}, {"Type": "Legacy", "Count": sum(stack['Legacy'].values())}])
fig_tech = px.bar(df_stack, x="Count", y="Type", color="Type", color_discrete_map={"Modern": "#111", "Legacy": "#888"})
fig_tech.update_layout(margin=dict(l=0,r=0,t=0,b=0), height=300, paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')

# 4. Salary by Platform
plat_stats = df[df['avg_salary'] > 0].groupby('source')['avg_salary'].median().sort_values(ascending=True)
fig_sal = px.bar(plat_stats, orientation='h', color_discrete_sequence=['#111'])
fig_sal.update_layout(margin=dict(l=0,r=0,t=0,b=0), height=300, xaxis_title="Median Salary (CZK)", paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')

# --- RENDER ---
output_html = html_template.format(
    date=datetime.date.today(),
    total_jobs=len(df),
    med_salary=med_sal_fmt,
    remote_share=remote_share,
    en_share=en_share,
    json_source=fig_vol.to_json(),
    json_contract=fig_cont.to_json(),
    json_tech=fig_tech.to_json(),
    json_salary=fig_sal.to_json()
)

# Ensure 'public' dir exists
os.makedirs("public", exist_ok=True)
with open("public/index.html", "w", encoding="utf-8") as f:
    f.write(output_html)

print("Static report generated: public/index.html")
